---
- name: Provision basics
  hosts: 127.0.0.1
  connection: local
  pre_tasks:  
  - name: Update the OS
    dnf:
      name: "*"
      state: latest
  - name: Install basic software
    dnf:
      name:
        - wget
        - vim
      state: latest
  # This is an example of how you can add roles into the playbook.
  # roles:
  # - role: ansible-role-elasticsearch
  #   vars:
  #     es_xpack_enabled: false
  #     es_tls_enabled: false
  #     es_node_fqdn: "{{ ansible_eth0.ipv4.address }}"